[env]
RUST_BACKTRACE = "full"

[env.FEATURES_FLAG]
value = ""
condition = { env_not_set = ["FEATURES_FLAG"] }

[tasks.clean]
description = "Clean target directory"
command = "cargo"
args = ["clean"]

[tasks.build]
description = "Run cargo build"
command = "cargo"
args = [
    "build",
    "--workspace",
    "@@split(FEATURES_FLAG, )"
]

[tasks.fmt]
condition = { channels = ["nightly"] }
description = "Check whether rust code is properly formatted or not"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
condition = { channels = ["nightly"] }
description = "Check if clippy return any warnings or error"
command = "cargo"
args = [
    "clippy",
    "--workspace",
    "@@split(FEATURES_FLAG, )",
    "--",
    "-D",
    "warnings",
]

[tasks.test]
description = "Run test"
command = "cargo"
args = [
    "test",
    "--workspace",
    "@@split(FEATURES_FLAG, )",
]

[tasks.local]
dependencies = ["fmt", "build", "clippy", "test"]

[tasks.full]
dependencies = ["clean", "local"]
