name: Build rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    strategy:
       matrix:
         include:
           - os: "ubuntu-latest"
             rust-version: "stable"
           - os: "macos-latest"
             rust-version: "stable"
           - os: "windows-latest"
             rust-version: "stable"
           - os: "ubuntu-latest"
             rust-version: "beta"
           - os: "ubuntu-latest"
             rust-version: "nightly"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
     - uses: actions/checkout@v4
     - name: Setup rust toolchain
       uses: dtolnay/rust-toolchain@master
       with:
         toolchain: ${{ matrix.rust-version }}
         components: rustfmt, clippy
     - name: Install cargo make
       uses: davidB/rust-cargo-make@v1
     - name: Run tests
       run: |
        cargo make full
