name: Publish
on:
  push:
    tags: "v*"

jobs:
  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish

  publish_release_note:
    name: Publish release note
    runs-on: ubuntu-latest
    needs: publish_crate

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --current --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ steps.git-cliff.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
